// news.js - Feature 9 扩展: 每日新闻摘要
// 复用 rss.js getAllFeeds() → 生成 MD 摘要 → 存 labos/news/YYYY-MM-DD.md
// Cordis-shaped: 导出 apply(ctx, config), W1 由 server.js 直接 import

import { getAllFeeds } from './rss.js'
import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const NEWS_DIR = join(__dirname, '..', 'labos', 'news')

// --- 生成每日摘要 MD,存盘 ---
export async function generateDailyDigest(dateStr) {
  const today = dateStr || new Date().toISOString().slice(0, 10)
  const items = await getAllFeeds()

  // 按来源分组
  const bySource = {}
  for (const item of items) {
    if (!bySource[item.source]) bySource[item.source] = []
    bySource[item.source].push(item)
  }

  // 构建 MD
  const lines = [`# Daily Research News - ${today}`, '']
  lines.push(`> Auto-generated by AutoProf LabOS at ${new Date().toISOString()}`)
  lines.push(`> Total items: ${items.length}`)
  lines.push('')

  for (const [source, feedItems] of Object.entries(bySource)) {
    lines.push(`## ${source} (${feedItems.length})`)
    lines.push('')
    for (const item of feedItems.slice(0, 15)) {
      const title = item.title.replace(/\n/g, ' ').trim()
      lines.push(`- [${title}](${item.link})`)
      if (item.pubDate) lines.push(`  - ${item.pubDate}`)
    }
    lines.push('')
  }

  const md = lines.join('\n')

  // 存盘
  try {
    mkdirSync(NEWS_DIR, { recursive: true })
    const filePath = join(NEWS_DIR, `${today}.md`)
    writeFileSync(filePath, md, 'utf-8')
    return { date: today, items: items.length, file: filePath }
  } catch (e) {
    console.error('[news] save digest failed:', e.message)
    return { date: today, items: items.length, error: e.message }
  }
}

// --- 读取某日摘要 ---
export function loadDailyNews(dateStr) {
  const today = dateStr || new Date().toISOString().slice(0, 10)
  const filePath = join(NEWS_DIR, `${today}.md`)
  if (existsSync(filePath)) {
    return { date: today, content: readFileSync(filePath, 'utf-8'), exists: true }
  }
  return { date: today, content: null, exists: false }
}

// --- 列出所有可用摘要 ---
export function listDailyNews() {
  try {
    const files = readdirSync(NEWS_DIR)
      .filter(f => f.endsWith('.md'))
      .map(f => f.replace('.md', ''))
      .sort().reverse()
    return files
  } catch {
    return []
  }
}

// --- Cordis 形态 ---
export function apply(ctx, config = {}) {
  ctx.service('news', {
    generate: (date) => generateDailyDigest(date),
    load: (date) => loadDailyNews(date),
    list: () => listDailyNews(),
  })
  ctx.on('ready', () => {
    ctx.logger?.info?.('news plugin ready')
  })
}

export default { generateDailyDigest, loadDailyNews, listDailyNews, apply }