import { appendFileSync } from 'fs'

const entry = [
  '',
  '---',
  '',
  '## 2026-08-20 21:06 — v0.7.4 学生端品牌切换 + 日历 + AI助手 + 知识库 + 本科生账号 [确定]',
  '',
  '### 问题',
  '',
  '前一个 session 修复了全局空白页根因（VERSION 不同步），但 student.js 仍缺少 student.html 引用的 brandName / 日历 / AI助手 / 知识库 逻辑，导致 Vue prod mode 静默空白页。',
  '',
  '### 改动',
  '',
  '| 文件 | 改动 | 置信度 |',
  '|---|---|---|',
  '| public/js/student.js | 新增 brandName computed（grad->AutoGrad, undergrad->AutoUngrad, teacher->AutoProf） | [确定] |',
  '| public/js/student.js | 新增日历模块（calendarMonth/Weekdays/Events/Label/Days + switchToCalendar/prevMonth/nextMonth，复用 teacher.js 逻辑） | [确定] |',
  '| public/js/student.js | 新增 AI 助手模块（assistantMessages/Input/Streaming + sendAssistantMessage SSE + loadAssistantHistory + mySummary + myReportHtml） | [确定] |',
  '| public/js/student.js | 新增知识库模块（kbFiles/Search/Loading/FilteredFiles + loadKb + viewKbFile + switchToKb） | [确定] |',
  '| public/js/student.js | validTabs 扩展为 7 项（+calendar/assistant/kb）+ hash 恢复 + return block 补全所有新 ref | [确定] |',
  '| public/student.html | student.js cache bust 073->074 | [确定] |',
  '| public/teacher.html | sidebar-logo EvoTeam->AutoProf | [确定] |',
  '| scripts/rebuild-student-js.mjs | 构建脚本（字符串替换方式修改 student.js，避免 PowerShell 转义） | [确定] |',
  '',
  '### 验证结果（浏览器 DOM 快照 + console error）',
  '',
  '| 角色 | 账号 | 品牌 | Tab 验证 | console error |',
  '|---|---|---|---|---|',
  '| 研究生 | s01/changeme | AutoGrad | 周报+任务+日历+AI助手+知识库 全部正常 | 0 |',
  '| 本科生 | u01/changeme | AutoUngrad | 周报正常（模板含 u01/本科生张三/本科创新训练） | 0 |',
  '',
  '日历 tab：2026年8月 网格 + 事件（组会/补充IEEE 33-bus实验数据）可见',
  'AI助手 tab：聊天历史加载 + AI 回复引用周报内容（V2G恢复/求解器收敛风险/文献综述不足）',
  '知识库 tab：文件列表（manager.json/students.yaml/tasks.json 等）+ 搜索框 + 刷新按钮',
  '',
  '### 未改动',
  '',
  '- 后端 lib/ 全部不动',
  '- server.js 不动（chat 路由已在前 session 放开 requireAuth）',
  '- VERSION 文件保持 0.7.3（未改 api.js APP_VERSION）',
  '',
].join('\n')

appendFileSync('D:/OneDrive/7-SideWork/AutoProf/DEVLOG.md', entry)
console.log('DEVLOG appended:', entry.length, 'chars')
